id: IFAFF4BB7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:48:56+00:00'
last_modified: '2022-06-08T04:20:29.184976+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4777
  title: ཕ་དམ་པ་སངས་རྒྱས་དང་མ་ཅིག་ལབ་སྒྲོན་གྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B031:
      image_group_id: I3CN4779
      title: Volume 1 of pha dam pa dang ma cig lab sgron gyi rnam thar/
      total_pages: 660
      order: 1
      base_file: B031.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
